### PR TITLE
add same information as in button-sensor

### PR DESCRIPTION
**Pull request by MattAtkinson**

### CODE REVIEW

**Comment by nikhil-zinjurde-imgtec** [comment]
Please create PR to dev branch first.  Once approved and verified on dev branch, the commits will be merged to master after further verification

**Comment by abhijit-mahajani-imgtec** [comment]
its a separate repo, same information commit does not help here

**Comment by MattAtkinson** [comment]
It's a change to the readme... It doesn't need further verification. The information is not exactly the same, it uses the same structure but with the button references changes to be appropriate.

**Comment by nikhil-zinjurde-imgtec** [comment]
But, we also need to keep both branches in sync

**Pull request closed without merging**
